version: '3.9'

services:
  mysql:
    image: mysql:5.7
    container_name: airflow_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airflow
      MYSQL_USER: airflow
      MYSQL_PASSWORD: airflow
    ports:
      - "3306:3306"
    volumes:
      - C:\projects\airflow_otodom\airflow\mysql:/var/lib/mysql
    command: --sql-mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
    networks:
      - airflow_network

  airflow-webserver:
    image: airflow_py:latest
    container_name: airflow_container
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=mysql+mysqlconnector://airflow:airflow@mysql:3306/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - C:\projects\airflow_otodom\airflow:/opt/airflow
    command: >
      bash -c " airflow db upgrade && airflow users create -r Admin -u admin -p admin -e admin@example.com -f Admin -l User && airflow webserver "
    restart: always
    networks:
      - airflow_network
    
  airflow-scheduler:
    image: airflow_py:latest
    depends_on:
      - mysql
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: mysql+mysqldb://airflow:airflow@mysql/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    volumes:
      - C:\projects\airflow_otodom\airflow:/opt/airflow
    command: >
      bash -c "
      airflow scheduler
      "
    restart: always
    networks:
      - airflow_network

networks:
  airflow_network:


volumes:
  mysql_data:
