FROM apache/airflow:2.9.2-python3.8

ENV PIP_USER=false

# Install dependencies:
COPY requirements.txt .

RUN python3 -m venv /opt/airflow/venv1
RUN /opt/airflow/venv1/bin/pip install --upgrade pip
RUN /opt/airflow/venv1/bin/pip install -r requirements.txt
RUN /opt/airflow/venv1/bin/pip install 'apache-airflow==2.4.1' --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.4.1/constraints-3.8.txt"

ENV PIP_USER=true