version: '3'

services:

  sleek-airflow:

    image: airflow:python3.8

    volumes:

      - C:\projects\small_scrapper\airflow:/opt/airflow

    ports:

      - "8080:8080"

    command: airflow standalone
